
POST https://oi7p8gbold.execute-api.eu-west-1.amazonaws.com/Prod/events/1/tickets/1/checkout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJraWQiOiJaMzdHVTdGdzBUXC90VmgrdEdJOGRtaUZ...
Origin: http://localhost:3000

{
  "quantity": 1,
  "email": "chants-change.7r@icloud.com",
  "discount_code": ""
}

###

GET https://oi7p8gbold.execute-api.eu-west-1.amazonaws.com/Prod/admin/ticket-orders HTTP/1.1
content-type: application/json
Authorization: Bearer eyJraWQiOiJaMzdHVTdGdzBUXC90VmgrdEdJOGRtaUZ...
Origin: http://localhost:3000

###